<?php
//时区设置
ini_set('date.timezone','Asia/Shanghai');
//常规状态码
define('SUCCESS',200);
define('FAIL',400);
define('REFUSE',403);
define('NOT_FIND',404);
define('REDIRECT',302);
define('BAD_REQUEST',501);
define('VIEW',9501);
define('PLAIN',9502);

//websocket码
define('ILLEGAL_LAND',102);//登陆信息非法
define('DISCONNECTED',103);//下线，特指客服
define('RECONNECTED',104);//重新上线，特指客服
define('EXTRUDED',105);//挤下线
define('CONNECTED',201);//连接成功
define('CLIENT_INFO',207);//客户最新信息
define('BIALOGUE_TRANSFER',208);//转接对话
define('END_DIALOGUE',209);//结束对话
